[project]
name = "elevator"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioconsole>=0.8.1",
    "pyside6>=6.9.0",
    "pyzmq>=26.4.0",
    "qasync>=0.27.1",
    "rich>=14.0.0",
    "tornado>=6.5.1",
]

[tool.ruff]
target-version = "py312"
